/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours;

import co.edu.uniandes.tours.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
