/*
 * generated by Xtext 2.10.0
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.toursdls.ui.internal.ToursdlsActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ToursdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ToursdlsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ToursdlsActivator.getInstance().getInjector(ToursdlsActivator.CO_EDU_UNIANDES_TOURSDSL);
	}
	
}
