/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ide

import co.edu.uniandes.ToursdslRuntimeModule
import co.edu.uniandes.ToursdslStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ToursdslIdeSetup extends ToursdslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ToursdslRuntimeModule, new ToursdslIdeModule))
	}
	
}
