/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DslRuntimeModule extends AbstractDslRuntimeModule {
}
