/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ide;

import co.edu.uniandes.ide.AbstractToursdslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ToursdslIdeModule extends AbstractToursdslIdeModule {
}
