/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ide;

import co.edu.uniandes.ToursdslStandaloneSetup;
import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ToursdslIdeSetup extends ToursdslStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from ToursdslIdeModule to Module");
  }
}
