/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ide;

import co.edu.uniandes.ToursdslRuntimeModule;
import co.edu.uniandes.ToursdslStandaloneSetup;
import co.edu.uniandes.ide.ToursdslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ToursdslIdeSetup extends ToursdslStandaloneSetup {
  @Override
  public Injector createInjector() {
    ToursdslRuntimeModule _toursdslRuntimeModule = new ToursdslRuntimeModule();
    ToursdslIdeModule _toursdslIdeModule = new ToursdslIdeModule();
    return Guice.createInjector(Modules2.mixin(_toursdslRuntimeModule, _toursdslIdeModule));
  }
}
