/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ToursdslIdeModule /* implements AbstractToursdslIdeModule  */{
}
