/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
