/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.toursdsl.impl;

import co.edu.uniandes.toursdsl.Panorama;
import co.edu.uniandes.toursdsl.Tour;
import co.edu.uniandes.toursdsl.ToursdslPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tour</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.toursdsl.impl.TourImpl#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.impl.TourImpl#getPlaces <em>Places</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.impl.TourImpl#getCOMMAplaces <em>COMM Aplaces</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TourImpl extends MinimalEObjectImpl.Container implements Tour
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getPlaces() <em>Places</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlaces()
   * @generated
   * @ordered
   */
  protected EList<Panorama> places;

  /**
   * The cached value of the '{@link #getCOMMAplaces() <em>COMM Aplaces</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCOMMAplaces()
   * @generated
   * @ordered
   */
  protected EList<Panorama> commAplaces;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TourImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ToursdslPackage.Literals.TOUR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ToursdslPackage.TOUR__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Panorama> getPlaces()
  {
    if (places == null)
    {
      places = new EObjectContainmentEList<Panorama>(Panorama.class, this, ToursdslPackage.TOUR__PLACES);
    }
    return places;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Panorama> getCOMMAplaces()
  {
    if (commAplaces == null)
    {
      commAplaces = new EObjectContainmentEList<Panorama>(Panorama.class, this, ToursdslPackage.TOUR__COMM_APLACES);
    }
    return commAplaces;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ToursdslPackage.TOUR__PLACES:
        return ((InternalEList<?>)getPlaces()).basicRemove(otherEnd, msgs);
      case ToursdslPackage.TOUR__COMM_APLACES:
        return ((InternalEList<?>)getCOMMAplaces()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ToursdslPackage.TOUR__NAME:
        return getName();
      case ToursdslPackage.TOUR__PLACES:
        return getPlaces();
      case ToursdslPackage.TOUR__COMM_APLACES:
        return getCOMMAplaces();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ToursdslPackage.TOUR__NAME:
        setName((String)newValue);
        return;
      case ToursdslPackage.TOUR__PLACES:
        getPlaces().clear();
        getPlaces().addAll((Collection<? extends Panorama>)newValue);
        return;
      case ToursdslPackage.TOUR__COMM_APLACES:
        getCOMMAplaces().clear();
        getCOMMAplaces().addAll((Collection<? extends Panorama>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ToursdslPackage.TOUR__NAME:
        setName(NAME_EDEFAULT);
        return;
      case ToursdslPackage.TOUR__PLACES:
        getPlaces().clear();
        return;
      case ToursdslPackage.TOUR__COMM_APLACES:
        getCOMMAplaces().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ToursdslPackage.TOUR__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case ToursdslPackage.TOUR__PLACES:
        return places != null && !places.isEmpty();
      case ToursdslPackage.TOUR__COMM_APLACES:
        return commAplaces != null && !commAplaces.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //TourImpl
