/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes;

import co.edu.uniandes.ToursdslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ToursdslStandaloneSetup extends ToursdslStandaloneSetupGenerated {
  public static void doSetup() {
    new ToursdslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
