/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.ui.tests;

import co.edu.uniandes.tours.ui.internal.ToursActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ToursActivator.getInstance().getInjector("co.edu.uniandes.tours.Dsl");
	}

}
