/**
 *
 * $Id$
 */
package Tours.validation;

import Tours.Coordenada;
import Tours.Panorama;

/**
 * A sample validator interface for {@link Tours.Hotspot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface HotspotValidator {
	boolean validate();

	boolean validateRotacion(Coordenada value);
	boolean validatePosicion(Coordenada value);
	boolean validateDestino(Panorama value);
	boolean validateOrigen(Panorama value);
	boolean validateNombre(String value);
}
