/**
 *
 * $Id$
 */
package Tours.validation;

import Tours.Coordenada;
import Tours.Hotspot;
import Tours.Panorama;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Tours.Tour}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TourValidator {
	boolean validate();

	boolean validatePanoramas(EList<Panorama> value);
	boolean validateHotspots(EList<Hotspot> value);
	boolean validateCoordenada(EList<Coordenada> value);
	boolean validateNombre(String value);
}
