/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.ide;

import co.edu.uniandes.tours.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
