/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.ide;

import co.edu.uniandes.tours.DslRuntimeModule;
import co.edu.uniandes.tours.DslStandaloneSetup;
import co.edu.uniandes.tours.ide.DslIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DslIdeSetup extends DslStandaloneSetup {
  @Override
  public Injector createInjector() {
    DslRuntimeModule _dslRuntimeModule = new DslRuntimeModule();
    DslIdeModule _dslIdeModule = new DslIdeModule();
    return Guice.createInjector(Modules2.mixin(_dslRuntimeModule, _dslIdeModule));
  }
}
