/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.toursdsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hotspot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.toursdsl.Hotspot#getName <em>Name</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.Hotspot#getDestino <em>Destino</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.Hotspot#getOrigen <em>Origen</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.Hotspot#getPosicion <em>Posicion</em>}</li>
 *   <li>{@link co.edu.uniandes.toursdsl.Hotspot#getRotacion <em>Rotacion</em>}</li>
 * </ul>
 *
 * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot()
 * @model
 * @generated
 */
public interface Hotspot extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link co.edu.uniandes.toursdsl.Hotspot#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Destino</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Destino</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destino</em>' reference.
   * @see #setDestino(Panorama)
   * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot_Destino()
   * @model
   * @generated
   */
  Panorama getDestino();

  /**
   * Sets the value of the '{@link co.edu.uniandes.toursdsl.Hotspot#getDestino <em>Destino</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destino</em>' reference.
   * @see #getDestino()
   * @generated
   */
  void setDestino(Panorama value);

  /**
   * Returns the value of the '<em><b>Origen</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Origen</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Origen</em>' reference.
   * @see #setOrigen(Panorama)
   * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot_Origen()
   * @model
   * @generated
   */
  Panorama getOrigen();

  /**
   * Sets the value of the '{@link co.edu.uniandes.toursdsl.Hotspot#getOrigen <em>Origen</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Origen</em>' reference.
   * @see #getOrigen()
   * @generated
   */
  void setOrigen(Panorama value);

  /**
   * Returns the value of the '<em><b>Posicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Posicion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Posicion</em>' containment reference.
   * @see #setPosicion(Coordenada)
   * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot_Posicion()
   * @model containment="true"
   * @generated
   */
  Coordenada getPosicion();

  /**
   * Sets the value of the '{@link co.edu.uniandes.toursdsl.Hotspot#getPosicion <em>Posicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Posicion</em>' containment reference.
   * @see #getPosicion()
   * @generated
   */
  void setPosicion(Coordenada value);

  /**
   * Returns the value of the '<em><b>Rotacion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rotacion</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rotacion</em>' containment reference.
   * @see #setRotacion(Coordenada)
   * @see co.edu.uniandes.toursdsl.ToursdslPackage#getHotspot_Rotacion()
   * @model containment="true"
   * @generated
   */
  Coordenada getRotacion();

  /**
   * Sets the value of the '{@link co.edu.uniandes.toursdsl.Hotspot#getRotacion <em>Rotacion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rotacion</em>' containment reference.
   * @see #getRotacion()
   * @generated
   */
  void setRotacion(Coordenada value);

} // Hotspot
