/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.ui;

import co.edu.uniandes.tours.ui.AbstractDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
