/*
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ToursdslStandaloneSetup extends ToursdslStandaloneSetupGenerated {

	def static void doSetup() {
		new ToursdslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
