/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.ui;

import co.edu.uniandes.ui.AbstractToursdslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ToursdslUiModule extends AbstractToursdslUiModule {
  public ToursdslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
