<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Tours" nsURI="http://www.uniandes.edu.co/Tours" nsPrefix="Tours">
  <eClassifiers xsi:type="ecore:EClass" name="Tour">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elemento" upperBound="-1"
        eType="#//Elemento"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pareja"/>
  <eClassifiers xsi:type="ecore:EClass" name="Panorama" eSuperTypes="#//Nodo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hotspots" lowerBound="1"
        upperBound="-1" eType="#//Hotspot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hotspot" eSuperTypes="#//Arco">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotación" lowerBound="1"
        eType="#//Coordenada"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posición" lowerBound="1"
        eType="#//Coordenada"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Destino"/>
  <eClassifiers xsi:type="ecore:EClass" name="Salida"/>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Nodo" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arco" eSuperTypes="#//Elemento"/>
  <eClassifiers xsi:type="ecore:EClass" name="Coordenada"/>
</ecore:EPackage>
