/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tests;

import co.edu.uniandes.toursdsl.Tour;
import org.junit.Test;
import org.junit.runner.RunWith;

/* @RunWith(/* name is null */)
@InjectWith(/* name is null */) */@SuppressWarnings("all")
public class ToursdslParsingTest {
  /* @Inject
   */private /* ParseHelper<Tour> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field ToursdslParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
