/**
 * generated by Xtext 2.12.0
 */
package co.edu.uniandes.tours.tours;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Position</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.edu.uniandes.tours.tours.Position#getPosx <em>Posx</em>}</li>
 *   <li>{@link co.edu.uniandes.tours.tours.Position#getPosy <em>Posy</em>}</li>
 *   <li>{@link co.edu.uniandes.tours.tours.Position#getPosz <em>Posz</em>}</li>
 * </ul>
 *
 * @see co.edu.uniandes.tours.tours.ToursPackage#getPosition()
 * @model
 * @generated
 */
public interface Position extends EObject
{
  /**
   * Returns the value of the '<em><b>Posx</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Posx</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Posx</em>' attribute.
   * @see #setPosx(double)
   * @see co.edu.uniandes.tours.tours.ToursPackage#getPosition_Posx()
   * @model
   * @generated
   */
  double getPosx();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tours.tours.Position#getPosx <em>Posx</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Posx</em>' attribute.
   * @see #getPosx()
   * @generated
   */
  void setPosx(double value);

  /**
   * Returns the value of the '<em><b>Posy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Posy</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Posy</em>' attribute.
   * @see #setPosy(double)
   * @see co.edu.uniandes.tours.tours.ToursPackage#getPosition_Posy()
   * @model
   * @generated
   */
  double getPosy();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tours.tours.Position#getPosy <em>Posy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Posy</em>' attribute.
   * @see #getPosy()
   * @generated
   */
  void setPosy(double value);

  /**
   * Returns the value of the '<em><b>Posz</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Posz</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Posz</em>' attribute.
   * @see #setPosz(double)
   * @see co.edu.uniandes.tours.tours.ToursPackage#getPosition_Posz()
   * @model
   * @generated
   */
  double getPosz();

  /**
   * Sets the value of the '{@link co.edu.uniandes.tours.tours.Position#getPosz <em>Posz</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Posz</em>' attribute.
   * @see #getPosz()
   * @generated
   */
  void setPosz(double value);

} // Position
